# This will be how basil knows a message is directed to him in group
# chats. Messages must be prefixed using "@me ", "me, " or similar.
me: basil

# This is the server type who's run method will be called. See
# ./lib/basil/servers/ for their definitions. Valid values at this time
# are :cli or :skype.
server_type: :cli

# This is the directory from which plugins are loaded. There can be one
# or more plugins per file and additional classes/logic may be present
# to support the contained plugins.
plugins_directory: ./plugins

# Required only on OSX and ruby 1.9 for https requests to work (JIRA).
# Install curl-ca-bundle via ports. The get_json utility will use this
# cert file for secure requests if the configuration option is present.
#https_cert_file: /opt/local/share/curl/curl-ca-bundle.crt

# Broadcasts are currently implemented by opening a TCP port and
# listening for incoming text.
broadcast_host: 127.0.0.1
broadcast_port: 1234

# Constants for the Jenkins API plugin.
jenkins_host:     jenkins1.ideeli.com
jenkins_port:     80
jenkins_user:     X
jenkins_password: X

# Constants for the Jira API plugin.
jira_host:     jira.ideeli.com
jira_port:     443
jira_user:     X
jira_password: X
